### ISSUE TITLE
安卓 欧朋   无法粘贴

### ISSUE THREAD

**Issue by sfrabbit** [AIWriter/AIWriterApp#2]
如题，粘贴没有反应

以及问下，怎么导出文章？

**Comment by badboy315** [comment]
@sfrabbit 感谢反馈, 收到建议.
1. 写匠由于是 内测 版, 在多浏览器版本中, 兼容性存在问题. 建议 PC 端使用 Chrome Firefox 浏览器;
2. 导出文章功能在未来版本中会陆续完善;
