### ISSUE TITLE
【疑问】新手看到写匠的批注，完全不知道怎么改

### ISSUE THREAD

**Issue by mrsunyi** [AIWriter/AIWriterApp#7]
有没有一些例子说明：
1.陈词滥调怎么改？大概有几种改法？
2.表意不明怎么改？大概有几种改法？
3.如何读懂长句子结构的分析图，然后优化自己的句子？
建议：
写匠的主界面左边，多一个【使用帮助】，有关于产品的具体用法和FAQ就好了

**Comment by yangshaoshun** [comment]
写匠现在只能给出标示，具体改法在认知写作学课程中有涉及。

优化的建议已转产品部门，多谢你的反馈。
